// This file is generated by CMake.
// Any modifications will be lost.
#ifndef SIMPLY_SIMPLY_HPP
#define SIMPLY_SIMPLY_HPP

#include <simply/concepts.hpp>
#include <simply/copyable.hpp>
#include <simply/destructible.hpp>
#include <simply/dispatch.hpp>
#include <simply/dyn.hpp>
#include <simply/elide.hpp>
#include <simply/extractable.hpp>
#include <simply/iface.hpp>
#include <simply/impl.hpp>
#include <simply/insertable.hpp>
#include <simply/invocable.hpp>
#include <simply/movable.hpp>
#include <simply/scope.hpp>
#include <simply/storage.hpp>
#include <simply/type_traits.hpp>
#include <simply/vtable.hpp>

#endif // SIMPLY_SIMPLY_HPP
