include_guard(GLOBAL)

file(
  GLOB_RECURSE SIMPLY_INCLUDES
  RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}/include
  CONFIGURE_DEPENDS include/simply/*.hpp)

list(REMOVE_ITEM SIMPLY_INCLUDES simply/simply.hpp)
list(TRANSFORM SIMPLY_INCLUDES PREPEND "#include <")
list(TRANSFORM SIMPLY_INCLUDES APPEND >)

string(JOIN "\n" SIMPLY_INCLUDES ${SIMPLY_INCLUDES})

file(
  CONFIGURE
  OUTPUT
  ${CMAKE_CURRENT_SOURCE_DIR}/include/simply/simply.hpp
  CONTENT
  "// This file is generated by CMake.\n// Any modifications will be lost.\n#ifndef SIMPLY_SIMPLY_HPP\n#define SIMPLY_SIMPLY_HPP\n\n${SIMPLY_INCLUDES}\n\n#endif // SIMPLY_SIMPLY_HPP\n"
)
